# Generated by Django 5.0.2 on 2024-02-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'Menu item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.SlugField(max_length=256, verbose_name='Url'),
        ),
    ]
